version: 2
jobs:
  build:
    working_directory: ~/dqduy/silkime
    docker:
        image: circleci/android:api-28
    environment:
        JVM_OPTS: -Xmx3200m
    branches:
        only:
    steps:
      - checkout
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
#         command: sudo chmod +x ./gradlew
      - run:
          name: Begin CI/CD
          command: |
            echo "Hello CI"
      - run:
          name: Download Dependencies
          command: ./java/project/gradlew androidDependencies