version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-28
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
         command: |
            sudo chmod +x ./java/project/gradlew
            sudo chmod +x ./make.sh
      - run:
          name: Build apk
          command: ./make.sh
      - run:
          name: List all files
          command: ls -l _generated/
